### ISSUE TITLE
オンラインのユーザを取得する

### ISSUE THREAD

**Issue by Mori-Atsushi** [Mori-Atsushi/YouTubeSyncServer#4]
GET /api/v1/rooms/:id にオンラインのユーザ一覧を追加する。
オンラインユーザを保持するモデルを作成する

```js
room {
  id: room.id,
  name: room.name,
  ...,
  now_playing_video: {
    id: video.id
    title: vidoe.title
    ...
  },
  last_video: {
    id: video.id
    title: vidoe.title
    ...
  }
 online_user: [{
    id: user.id,
    name: user.name
  }, {
    id: user.id,
    name: user.name
    ...
 }]
}
```

**Comment by Mori-Atsushi** [comment]
オンラインユーザの保持方法ってどうしよ。

## 案１ ログ方式

| ユーザID | ルームID | 入室時間 | 退室時間 | 状態 |
----|----|----|----|---- 
| 1 | 1 | 2017/11/03 8:46 | 2017/11/03 8:50 | false |
| 1 | 1 | 2017/11/03 8:55 | null | true |

ルーム参加の状況を全てログとして残す。
参加していると状態がture、ルームから抜けるとfalseになる。
trueのものを探せばオンラインユーザが見つかる。

## 案２ オンラインユーザテーブル

| ユーザID | ルームID | 入室時間 | 
----|----|---- 
| 1 | 1 | 2017/11/03 8:46 |
| 2 | 1 | 2017/11/03 8:55 |

参加しているユーザのみをテーブルに保存し、ルームから抜けるとデータを消す。

**Comment by euglena1215** [comment]
保持する内容はsessionに近いと思うから案2のデータをKVS(Redisとか)に持たせるのが形としては綺麗かなって思う。

テーブルとして持たせたいのであれば案1になるのかなーって感じ。
退室時間がnullかnot nullかで状態は判断できるからいらない気がする。

**Comment by Mori-Atsushi** [comment]
#7 も実装することを考えるとどうなんだろう

**Comment by chigichan24** [comment]
過去入室ルーム10件ってこの形だと取得できなくないですか？

**Comment by Mori-Atsushi** [comment]
案2だったらユーザーで絞り込んで重複除けばいけるくない？

**Comment by chigichan24** [comment]
たしかにね．じゃあ2がいいんじゃないですか @euglena1215 も言ってるわけだし．

**Comment by Mori-Atsushi** [comment]
間違えた、案2だと退室したらデータ消えちゃうからだめだ。
案1なら実装可能じゃない？

**Comment by chigichan24** [comment]
あ．なるほどね．じゃあログ残さないとダメですね．いなくなったら2はデータ消すのね．適度なタイミングでログと同期しながらの運用とかできないかしら > @euglena1215

**Comment by euglena1215** [comment]
@chigichan24 
> 適度なタイミングでログと同期しながらの運用

それこそ案2の形式をKVSに載せつつ、案2を入室ユーザログテーブルとしてinsertし続けていく形になるような気がする
退室したかどうかはKVSに完全に任せるのが良さそう

個人的にはとりあえずテーブルだけの案1で実装してみてパフォーマンス的に問題があれば案2でいい感じにするって方針でいいと思う
